version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dockerwithnest
      - POSTGRES_PASSWORD=dockerwithnest
      - POSTGRES_DB=nest
    volumes:
      - users_pg_data:/bitnami/postgresql

volumes:
  users_pg_data:
